name: Go Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: |
        cd backend
        go mod download

    - name: Run Go tests
      run: |
        cd backend
        # As variáveis de ambiente do DB são usadas pelos testes de integração
        export POSTGRES_USER=${{ secrets.POSTGRES_USER || 'testuser' }}
        export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD || 'testpassword' }}
        export POSTGRES_DB=${{ secrets.POSTGRES_DB || 'testdb' }}
        export DATABASE_HOST=localhost
        export DATABASE_PORT=5432
        export JWT_SECRET_KEY=test-secret
        go test -v ./...