version: '3.8'

services:
  # Serviço do Backend (Go API)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go_api
    ports:
      - "8080:8080"
    # volumes:
    #  - ./backend:/app # Mapeia o código local para o container para live-reloading
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  # Serviço do Frontend (Vue.js com Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_ui
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  # Serviço do Banco de Dados (PostgreSQL)
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: